services:

  demo-mysql:
    image: mysql:8
    container_name: demo-mysql
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: Abcd.1234#
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: demo-backend
    depends_on:
      demo-mysql:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    container_name: demo-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
